from __future__ import annotations

from enum import IntEnum


INSTRUCTION_WIDTH_BITS = 16
REGISTER_WIDTH_BITS = 64
REGISTER_COUNT = 16
FLAG_Z = 0
FLAG_C = 1
FLAG_S = 2

CPU_CONTROL_INT_ENABLE = 1 << 0
CPU_CONTROL_IN_INTERRUPT = 1 << 1
CPU_CONTROL_CUR_INT_SHIFT = 2
CPU_CONTROL_CUR_INT_MASK = 0x7F << CPU_CONTROL_CUR_INT_SHIFT
CPU_CONTROL_PAGING_ENABLE = 1 << 16
CPU_CONTROL_USER_MODE = 1 << 17
CPU_CONTROL_WRITABLE_MASK = (
    CPU_CONTROL_INT_ENABLE |
    CPU_CONTROL_IN_INTERRUPT |
    CPU_CONTROL_CUR_INT_MASK |
    CPU_CONTROL_PAGING_ENABLE |
    CPU_CONTROL_USER_MODE
)


class LSOpcode(IntEnum):
    LOAD = 0
    STORE = 1
    PUSH = 2
    POP = 3
    MOVE = 4
    BYTE_LOAD = 5
    BYTE_STORE = 6
    SHORT_LOAD = 7
    SHORT_STORE = 8
    WORD_LOAD = 9
    WORD_STORE = 10
    JUMP_Z = 11
    JUMP_C = 12
    JUMP_S = 13
    JUMP_GT = 14
    JUMP_LT = 15


class GPOpcode(IntEnum):
    ADD = 0
    SUB = 1
    TEST = 2
    LLR = 3
    SCR = 4
    AND = 16
    OR = 17
    XOR = 18
    SLL = 20
    SRL = 21
    SRA = 22
    SLLI = 23
    SRLI = 24
    SRAI = 25
    SYSCALL = 27
    LSR = 28
    SSR = 29
    IRET = 30
    STOP = 31


class TrapVector(IntEnum):
    EXEC_ALIGN = 1
    PRIVILEGED_INSTRUCTION = 2
    SYSCALL = 3
    SYSCALL_FROM_SUPERVISOR = 4
    PAGE_FAULT_NOT_PRESENT = 5
    PAGE_FAULT_PERMISSION = 6
    PAGE_FAULT_RESERVED = 7
    PAGE_FAULT_CANONICAL = 8
    INVALID_INSTRUCTION = 9
    FIRST_HW_IRQ = 65


class SpecialRegister(IntEnum):
    CPU_CONTROL = 0
    PAGE_TABLE_ROOT_PHYSICAL = 11
    BOOT_INFO_FRAME_PHYSICAL = 12
    BOOT_SOURCE_PAGE_SIZE = 13
    BOOT_SOURCE_PAGE_COUNT = 14
    HYPERCALL_CAPS = 15
    INTERRUPT_TABLE_BASE = 16
    INTERRUPT_MASK = 17
    INTERRUPT_MASK_HIGH = 18
    INTERRUPT_STATES = 19
    INTERRUPT_STATES_HIGH = 20
    INTERRUPT_EPC = 21
    INTERRUPT_EFLAGS = 22
    INTERRUPT_CPU_CONTROL = 23
    TRAP_CAUSE = 24
    TRAP_FAULT_ADDR = 25
    TRAP_ACCESS = 26
    TRAP_PC = 27
    TRAP_AUX = 28
    THREAD_POINTER = 0x8000
